
public class TestData {
	public static void load(){
		ObjectStore os = ObjectStore.getInstance();
		VideoTitle title;
		VideoEntity entity;
		Staff staff;
		Member member;
		title = new VideoTitle("24 - Season I - Vol1");
		title.setIdentifier("T012001");
		title.setMediaType(MediaType.DVD);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01200101");
		os.saveVideoEntity(entity);
		title = new VideoTitle("24 - Season I - Vol2");
		title.setIdentifier("T012002");
		title.setMediaType(MediaType.DVD);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01200201");
		os.saveVideoEntity(entity);
		title = new VideoTitle("24 - Season I - Vol3");
		title.setIdentifier("T012003");
		title.setMediaType(MediaType.DVD);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01200301");
		os.saveVideoEntity(entity);
		title = new VideoTitle("24 - Season I - Vol4");
		title.setIdentifier("T012004");
		title.setMediaType(MediaType.DVD);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01200401");
		os.saveVideoEntity(entity);
		title = new VideoTitle("24 - Season I - Vol5");
		title.setIdentifier("T012005");
		title.setMediaType(MediaType.DVD);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01200501");
		os.saveVideoEntity(entity);
		title = new VideoTitle("Hurry Potter Part1");
		title.setIdentifier("T013101");
		title.setMediaType(MediaType.BluRay);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310101");
		os.saveVideoEntity(entity);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310102");
		os.saveVideoEntity(entity);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310103");
		os.saveVideoEntity(entity);
		title = new VideoTitle("Hurry Potter Part2");
		title.setIdentifier("T013102");
		title.setMediaType(MediaType.BluRay);
		os.saveVideoTitle(title);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310201");
		os.saveVideoEntity(entity);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310202");
		os.saveVideoEntity(entity);
		entity = new VideoEntity(title);
		entity.setIdentifier("E01310203");
		os.saveVideoEntity(entity);
		
		staff = new Staff("Bill Gates");
		os.saveStaff(staff);
		staff = new Staff("Steve Jobs");
		os.saveStaff(staff);
		staff = new Staff("Tim Cook");
		os.saveStaff(staff);
		member = new Member("Ichiro Suzuki");
		os.saveMember(member);
		member = new Member("Taro Momo");
		os.saveMember(member);
		member = new Member("Jiro Ramen");
		os.saveMember(member);
	}
}
